---
# 1. Verificar autenticación con Azure CLI
- name: Verificar autenticación con Azure CLI
  command: az account show
  register: azure_account
  changed_when: false
  failed_when: azure_account.rc != 0

# 2. Login en el ACR
- name: Login en el ACR
  containers.podman.podman_login:
    registry: "{{ acr_url }}"
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"

# 3. Descargar imagen nginx desde Docker Hub
- name: Descargar imagen nginx:latest desde Docker Hub
  containers.podman.podman_image:
    name: docker.io/library/nginx:latest

# 4. Etiquetar imagen nginx para el ACR
- name: Etiquetar imagen nginx para el ACR
  command: >
    podman tag docker.io/library/nginx:latest {{ acr_url }}/nginx:casopractico2

# 5. Subir imagen nginx al ACR
- name: Subir imagen nginx al ACR
  command: >
    podman push {{ acr_url }}/nginx:casopractico2
